/*
 * rprintmsg.c: remote version of "printmsg.c"
 *
 * Source: ?Using rpcgen?, http://www.cisco.com/en/US/docs/ios/sw_upgrades/interlink/r2_0/rpc_pr/rprpcgen.html
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <rpc/rpc.h>	/* always needed */
#include "msg.h"	/* need this too: msg.h will be generated by rpcgen */

int main(int argc, char *argv[])
{

	CLIENT *cl;
	int *result;
	char *server;
	char *command;
	char *message;


	char **the_response;

	if (argc < 3) {
		fprintf(stderr, "usage: %s host message\n", argv[0]);
		exit(1);
	}

	/*
	 * Save values of command line arguments
	 */

	server = argv[1];
	command = argv[2];
	message = argv[3];


	// if(strcmp(command, "-s") == 0){
	// 	printf("=\n");
	// }
	// else if(strcmp(command, "-s") > 0){
	// 	printf(">\n");
	// }
	// else if(strcmp(command, "-s") < 0){
	// 	printf("<\n");
	// }


	/*
	 * Create client "handle" used for calling MESSAGEPROG on the
	 * server designated on the command line. We tell the RPC package
	 * to use the "tcp" protocol when contacting the server.
	 */

	cl = clnt_create(server, MESSAGEPROG, MESSAGEVERS, "tcp");
	if (cl == NULL) {
		/*
		 * Couldn't establish connection with server.
		 * Print error message and die.
		 */
		clnt_pcreateerror(server);
		exit(1);
	}


	if(strcmp(command, "-a") == 0){
	/*
	 * Call the remote procedure "printmessage" on the server
	 */
	 result = printmessage_1(&message, cl);
	 if (result == NULL) {
		/*
		 * An error occurred while calling the server.
		 * Print error message and die.
		 */
		 clnt_perror(cl, server);
		 exit(1);
		}

	/*
	 * Okay, we successfully called the remote procedure.
	 */
	 if (*result == 0) {
		/*
		 * Server was unable to print our message.
		 * Print error message and die.
		 */
		 fprintf(stderr, "%s: %s couldn't print your message\n",
		 	argv[0], server);
		 exit(1);
		}

	/*
	 * The message was output on the server
	 */
	 printf("Message delivered to %s!\n", server);

	 return 0;
	}

    else if(strcmp(command, "-c") == 0){
    	//Call count
    	 result = count_1(&message, cl);
    	 if (result == NULL) {
    		//error occured
    		 clnt_perror(cl, server);
    		 exit(1);
    		}

    	 if (*result == 0) {
    		/*
    		 * Server was unable to print our message.
    		 * Print error message and die.
    		 */
    		 fprintf(stderr, "%s: %s unable to count\n", argv[0], server);
    		 exit(1);
    		}

    	//Search was successful
    	 printf("The word occured %d!\n", *result);

    	 return 0;
    	}



else if(strcmp(command, "-s") == 0){
	//Call search
	char **returned;
	char **newMessage = &message;
	returned = search_1(newMessage, cl);
	 if (returned == NULL) {
		//Couldn't find it
		printf("Couldn't find it\n");
		return 0;
	}

	//Search was successful
	 printf("Found sentence: %s\n", *returned);
	 return 1;
	}


else if (strcmp(command, "-f") == 0){

	char **response;
	char* end;
	int index = strtol(message, &end, 10);

	if(!*end){
	response = find_1(&index, cl);
	if(response == NULL){
		printf("Unable to find sentence with index %d\n", index);
		return 0;
	}

	printf("Got sentence: %s\n", *response);
	exit(1);
	return 0;
	}
	else{
		printf("unable to convert input to integer: %s\n", end);
		return 0;
	}
	
}




	else if(strcmp(command, "-r") == 0){
	//Call remove
	char **response;
	response = remove_string_1(&message, cl);

	printf("%s\n", *response);
	return 0;

	// //Search was successful
	//  printf("Message found the sentence:  \n");
	//  while(strcmp(*response, ".") != 0){
	//  	printf("%s", *response);
	//  }

	//  return 0;
	}




	else if(strcmp(command, "-d") == 0){
	//Call remove
	char **response;
	printf("calling thing\n");
	response = delete_1(&message, cl);
	printf("called thing\n");

	printf("printing thing\n");
	printf("%s\n", *response);
	printf("printed thing\n");
	free(*response);
	return 0;
	}




}





